
import html2text
text_maker = html2text.HTML2Text()
text_maker.ignore_links = True
text_maker.ignore_images = True

html = '<img align="left" hspace="8" src="https://img.olhardigital.com.br/uploads/acervo_imagens/2020/05/r4x3/20200515115854_860_645_-_tsmc.jpg"><br/><p dir="ltr">A <a href="https://olhardigital.com.br/games-e-consoles/noticia/processo-contra-a-tsmc-pode-prejudicar-suprimento-de-chips-da-apple/89593">TSMC</a> (Taiwan Semiconductor Manufacturing Company), que fabrica processadores para a <a href="https://olhardigital.com.br/noticia/homem-processa-a-apple-acusando-a-empresa-de-torna-lo-gay/91071">Apple</a>, vai investir US$ 12 bilhões em uma fábrica de chips no Arizona, EUA. Será seu segundo local de produção naquele país, onde também possui uma fábrica em Washington.</p><p dir="ltr">A empresa usará sua mais recente tecnologia de <a href="https://olhardigital.com.br/noticia/fornecedor-da-apple-se-prepara-para-produzir-chips-em-5-nanometros/97900">fabricação de 5 nanômetros</a> com capacidade para produzir 20 mil peças de semicondutores por mês. Como esperado, a construção será subsidiada pelo <a href="https://olhardigital.com.br/fique_seguro/noticia/hackers-iranianos-invadem-site-do-governo-dos-eua/94974">governo dos EUA</a> e criará 1.600 empregos. </p><p dir="ltr"><figure><img src="https://cache.olhardigital.com.br/uploads/acervo_imagens/2019/04/20190415093148.jpg" width="1100" height="700"><figcaption><span class="copyright">Reprodução</span></figcaption></figure></p><p dir="ltr"><em>Chip A13 da Apple/Foto: Apple</em></p><p dir="ltr">As negociações com o governo americano acontecem há meses, mas o alto custo de construção da <a href="https://olhardigital.com.br/noticia/xiaomi-esta-construindo-fabrica-totalmente-automatizada-na-china/96827">fábrica</a> sempre foi um ponto de discórdia das conversas. O presidente da TSMC, Mark Liu, disse ao <em>NY Times</em> no ano passado que, como é mais caro operar nos EUA do que em Taiwan, a empresa exigiria grandes subsídios. No entanto, não há relatos da quantia que o governo injetará na fábrica.</p><p dir="ltr">De acordo com a TSMC, a construção terá início em 2021, com produção prevista para começar em 2024.</p><p dir="ltr">Via: <em><a href="https://www.engadget.com/tsmc-12-billion-chip-plant-arizona-083518143.html">Engadget</a></em></p><div> </div>'

def cleanText(text):
    text = text_maker.handle(text)
    return text

print(cleanText(html))